server:
  port: ${PORT:8085}  # Valor por defecto si PORT no está configurado
  url: ${SERVER_URL:https://fuzzy-broccoli-wp475v45r5j394p7-8085.app.github.dev}  # Valor por defecto si SERVER_URL no está configurado

spring:
  application:
    name: API-AI
  r2dbc:
    url: r2dbc:postgresql://neondb_owner:npg_VLw14dKbnlIx@ep-withered-bird-aca8elbd-pooler.sa-east-1.aws.neon.tech/apiai?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_VLw14dKbnlIx

rapidapi:
  youtube-mp36:
    url: https://youtube-mp36.p.rapidapi.com
    host: youtube-mp36.p.rapidapi.com
    apikey: 11d5a59a70msh928a6b51895e702p12ab87jsn7b4f24c628ba

  instagram120:
    url: https://instagram120.p.rapidapi.com
    host: instagram120.p.rapidapi.com
    apikey: 11d5a59a70msh928a6b51895e702p12ab87jsn7b4f24c628ba



logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.web.reactive.function.client: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
